apiVersion: v1
entries:
  firstchart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-11-13T22:16:49.8810307-05:00"
    dependencies:
    - name: mysql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - enabled
      version: ^9.0.0
    description: A Helm chart for Kubernetes
    digest: cf707bcbd7d2edee3f15a6cd95eb0ed827057e194a03e198d455517b37093175
    name: firstchart
    type: application
    urls:
    - firstchart-0.1.0.tgz
    version: 0.1.0
  secondchart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-11-13T22:16:49.8878409-05:00"
    description: A Helm chart for Kubernetes
    digest: 8fb8343f7b009ed114b16a6d25a3c85f3ae54bea40376291b17c84f255787fe4
    name: secondchart
    type: application
    urls:
    - secondchart-0.1.0.tgz
    version: 0.1.0
generated: "2022-11-13T22:16:49.8668154-05:00"
