apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "firstchart.fullname" . }}-pre-install"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  containers:
    - name: pre-install-cont
      image: busybox
      imagePullPolicy: IfNotPresent
      command:
        - "sh"
        - "-c"
        - "echo Pod is running"
  restartPolicy: OnFailure
