apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auto-sync-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: auto-sync-app
    server: "https://kubernetes.default.svc"
  source:
    path: guestbook-with-subdirectories
    repoURL: "https://github.com/nguyen-gia-hien-tu/argocd-example-apps.git"
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
