apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-dev-project
  namespace: argocd
spec:
  destination:
    # namespace: test-1 # different from destinations.namespace in "project - whitelist namespace.yaml"
    namespace: ns-1 # the same as destinations.namespace in "project - whitelist namespace.yaml"
    server: "https://kubernetes.default.svc"
  project: dev-project
  source:
    path: guestbook
    repoURL: "https://github.com/mabusaa/argocd-example-apps.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  
