apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-with-role-project
  namespace: argocd
spec:
  destination:
    namespace: app-with-role-project
    server: "https://kubernetes.default.svc"
  project: project-with-role
  source:
    path: guestbook
    repoURL: "https://github.com/mabusaa/argocd-example-apps.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
